on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s" -o dot
      - run: tar -acf dot.tar.xz dot
      - uses: softprops/action-gh-release@v2
        with:
          files: dot.tar.xz
      - uses: noClaps/homebrew-tap-action@v1.1.0
        with:
          tap_repo: noClaps/homebrew-tap
          formula_name: dot
          version: ${{ github.ref_name }}
          tap_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          macos_file: dot.tar.gz
          completion_command: "--completions"
